# Generated by Django 5.1.2 on 2024-11-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_make_car_description_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Description',
            new_name='Make',
        ),
    ]
