# Generated by Django 5.1.2 on 2024-11-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_description_car_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Make',
            new_name='make',
        ),
    ]
