# Generated by Django 5.1.2 on 2024-12-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_invoice_is_paid_invoice_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_date',
        ),
    ]
